// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdnZRG_pqrDgHrPpg13Tawrp5rzBiA80k',
    appId: '1:187325939086:web:2ea6e28b4e4d60c477b8df',
    messagingSenderId: '187325939086',
    projectId: 'kutumba8',
    authDomain: 'kutumba8.firebaseapp.com',
    storageBucket: 'kutumba8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1f1k-K7GarH4FGopnvJf3JYPhilE1qXc',
    appId: '1:187325939086:android:157ae7910bb5a57b77b8df',
    messagingSenderId: '187325939086',
    projectId: 'kutumba8',
    storageBucket: 'kutumba8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6cEoDD1J4FA2HddbJInAJZ7t00WcF1F8',
    appId: '1:187325939086:ios:4a8939e6680e59ea77b8df',
    messagingSenderId: '187325939086',
    projectId: 'kutumba8',
    storageBucket: 'kutumba8.firebasestorage.app',
    iosBundleId: 'Asteriskhubs.Kutumba',
  );
}
